import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contextapi";

const lato = Lato({ subsets: ["latin-ext"], weight: "400" });

export const metadata: Metadata = {
  title: "PHS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={lato.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
